try 2

diff --git a/.github/workflows/feature-tests.yml b/.github/workflows/feature-tests.yml
--- a/.github/workflows/feature-tests.yml
+++ b/.github/workflows/feature-tests.yml
@@ -66,4 +66,4 @@ jobs:
           DB_DATABASE: laravel
           DB_USERNAME: laravel
           DB_PASSWORD: secret
-        run: php artisan test
+        run: php artisan test -v || (echo "::error::Tests failed" && exit 1)
